services:
  - type: web
    name: django-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
