name: Run Weatherproject Docker Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and run the custom Weatherproject Docker action
      - name: Run Weatherproject Docker Action
        uses: ./.github/actions
        with:
          port: 8000
